packages:
  - zod-sockets
  - example
  - cjs-test
  - esm-test
  - compat-test
  - issue952-test
gitChecks: false
engineStrict: true
autoInstallPeers: false
publicHoistPattern:
  - "@vitest/*"
  - "@eslint/*"
  - "globals"
catalogs:
  prod:
    "ansis": "^4.0.0"
    "ramda": "^0.32.0"
    "yaml": "^2.4.1"
  peer:
    "socket.io": "^4.7.4"
    "typescript": "^5.3.3"
    "zod": "^4.1.0"
  dev:
    "socket.io": "^4.7.4"
    "socket.io-client": "^4.7.4"
    "typescript": "^5.3.3"
    "zod": "^4.1.0"
overrides:
  "@scarf/scarf": "npm:empty-npm-package@1.0.0"
