name: AsyncAPI Validation

on:
  push:
    branches: [ main, make-v6 ]
  pull_request:
    branches: [ main, make-v6 ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - uses: pnpm/action-setup@v5
    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: pnpm
    - name: Installing unreasonably large package
      run: pnpm add -g @asyncapi/cli
    - name: Validate
      run: asyncapi validate ./example/example-documentation.yaml
