name: AsyncAPI Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: none
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - uses: pnpm/action-setup@v6
    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: pnpm
    - name: Installing unreasonably large package
      run: pnpm add -g @asyncapi/cli --config.minimum-release-age=1440
    - name: Validate
      run: asyncapi validate ./example/example-documentation.yaml
