name: AsyncAPI Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: none
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - uses: pnpm/action-setup@v6
    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: pnpm
    - name: Install CLI tool and Validate
      run: |
        pnpm dlx --config.minimum-release-age=0 @asyncapi/cli@6 \
          validate ./example/example-documentation.yaml
