name: Minor

on: workflow_dispatch

permissions:
  contents: write

jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - uses: fregante/setup-git-user@v2
      - run: |
          pnpm install
          pnpm hooks
      - run: npm version minor
