# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.0.0, 18.x, 20.0.0, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Get yarn cache dir
      id: yarnCache
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v4
      env:
        cache-name: cache-yarn
      with:
        path: ${{ steps.yarnCache.outputs.dir }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Unit test
      run: yarn test
    - name: System test
      run: yarn test:system
    - name: Build
      run: yarn build
    - name: CJS test
      run: yarn test:cjs
    - name: ESM test
      run: yarn test:esm
    - name: Compatibility test
      run: yarn test:compat
    - name: Issue 952 # see https://github.com/RobinTail/express-zod-api/issues/952
      run: yarn test:952
